spring.application.name=practiceProjectSpring
spring.datasource.url=jdbc:mysql://localhost:3306/practiceProjectSpring_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=suloy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#configure Kafka
spring.kafka.bootstrap-servers=localhost:9092


#Kafka ultimately works with bytes. The key uses StringSerializer, \
#  which converts the String directly into bytes. The value uses JsonSerializer, \
#  which converts the Java object into JSON and then serializes it into bytes.

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer